import { ProjectDetailType } from "../types/projectDetail";

export const projectDetail: ProjectDetailType[] = [
  {
    id: "yolda-user",
    name: "열다 서비스 페이지",
    state: "PARTIAL_OPEN",
    github: "https://github.com/tmdgp0212/FE_DAMDA",
    demoSite: "https://fe-damda.vercel.app/",
    duration: "23.05.30 ~ 23.06.28",
    language: ["NextJS", "TypeScript"],
    library: [
      "React-Query",
      "Axios",
      "Zustand",
      "React-hook-form",
      "swiperjs",
      "emotion",
    ],
    worker: "FE 4인 , BE 3인",
    summary: `(주)열다컴퍼니와 함께한 기업연계 프로젝트입니다.
옷장 정리 및 중고 의류 판매 대행 서비스를 제공하는 열다컴퍼니의 서비스 페이지 제작 및 기존 열다의 분산되어 있던 업무 프로세스를 통합하고 구조화하기 위한 어드민 페이지 제작을 진행하였습니다.`,
    works: [
      "카카오 Oauth 소셜 로그인 구현",
      "공통 컴포넌트(헤더, Nav 메뉴 등) 제작",
      "고객후기 페이지, 서비스 완료 폼 제작",
    ],
  },
  {
    id: "yolda-admin",
    name: "열다 어드민 페이지",
    state: "DOWN",
    github: "https://github.com/tmdgp0212/FE_DAMDA-admin",
    demoSite: "https://fe-damda-admin.vercel.app/",
    duration: "23.05.30 ~ 23.06.28",
    language: ["NextJS", "TypeScript"],
    library: [
      "React-Query",
      "Axios",
      "Zustand",
      "React-hook-form",
      "swiperjs",
      "emotion",
    ],
    worker: "FE 4인 , BE 3인",
    summary: `(주)열다컴퍼니와 함께한 기업연계 프로젝트입니다.
옷장 정리 및 중고 의류 판매 대행 서비스를 제공하는 열다컴퍼니의 서비스 페이지 제작 및 기존 열다의 분산되어 있던 업무 프로세스를 통합하고 구조화하기 위한 어드민 페이지 제작을 진행하였습니다.`,
    works: [
      "카카오 Oauth 소셜 로그인 구현",
      "공통 컴포넌트(헤더, Nav 메뉴 등) 제작",
      "고객 관리 페이지, 고객후기 관리 페이지 제작",
    ],
  },
  {
    id: "vacation-manager",
    name: "연차 관리 프로그램",
    state: "DOWN",
    github: "https://github.com/tmdgp0212/FE_Mini",
    demoSite: "",
    duration: "23.05.01 ~ 23.05.17",
    language: ["react", "typescript"],
    library: [
      "axios",
      "react-query",
      "msw",
      "react-big-calendar",
      "react-router-dom",
      "redux",
      "react-hook-form",
      "emotion",
      "mui",
    ],
    worker: "FE 5인, BE 4인",
    summary:
      "사원들은 연차 혹은 당직을 신청하고 관리자는 해당 당직과 연차에 대한 승인권한을 가지도록 하는 연차/당직 관리 프로그램입니다",
    works: [
      "react-big-calendar 를 가공하여 등록 된 연차와 당직 정보가 표시 되도록 커스텀",
      "msw mock api 생성",
      "관리자 페이지의 유저정보 검색 및 수정 기능 구현",
      "관리자 페이지의 직급 / 부서 관리 페이지 구현",
      "페이지의 전체적인 통일성 유지를 위한 레이아웃 / 디자인 컨벤션 작성",
    ],
  },
  {
    id: "moodlog",
    name: "Moodlog",
    state: "DOWN",
    github: "https://github.com/REACT-2",
    demoSite: "",
    duration: "23.04.17 ~ 23.04.28",
    language: ["React", "TypeScript"],
    library: [
      "React-router-dom",
      "React-Query",
      "Axios",
      "Zustand",
      "React-hook-form",
      "React-Cookie",
      "Styled-components",
      "React-icons",
    ],
    worker: "4인",
    summary: `무드로그는 다양한 무드 아이콘과 함께 나의 하루를 그림으로 기록할 수 있는 소셜 네트워크 서비스입니다.
무드로그를 통해 나의 하루를 생생하게,다양한 시각으로 바라볼 수 있습니다.`,
    works: [
      "포스트 상세보기, 댓글 작성 페이지 및 유저 검색 페이지 구현",
      "전체 API를 모듈화하여 재사용성을 높임 ",
      "Node와 express를 활용하려 JWT방식의 유저 인증 및 유저 테이블 관련 기능 설계 및 구현",
    ],
  },
  {
    id: "next-furniture",
    name: "Next Furniture",
    state: "OPEN",
    github: "https://github.com/tmdgp0212/KDT-M4_Team2Project_Repo",
    demoSite: "https://next-furniture.vercel.app/",
    duration: "2023. 01. 30 ~ 2023.03.03",
    language: ["HTML", "Scss", "JavaScript"],
    library: ["node-fetch", "Swiper", "Navigo", "Vercel"],
    worker: "5인",
    summary:
      "가구 쇼핑몰 NEXT FURNITURE 입니다. 관리자는 가구 정보의 등록/수정이 가능합니다.",
    works: [
      "메인페이지 구현",
      "검색 페이지 및 카테고리 별 가구페이지 구현",
      "마이 페이지 > 나의 정보 페이지 구현",
      "페이지 전체적인 레이아웃 수정",
    ],
  },
  {
    id: "fine-dust",
    name: "미세먼지 알리미",
    state: "OPEN",
    github: "https://github.com/tmdgp0212/FineDustMap",
    demoSite: "https://whimsical-sfogliatella-62bbe0.netlify.app/",
    duration: "23.03.24 ~ 23.03.27",
    language: ["react"],
    library: ["redux", "axios", "react-router-dom", "styled-component"],
    worker: "1인",
    summary: "시/도별 미세먼지 정보를 조회할 수 있는 미세먼지 알리미 앱 입니다",
    works: [
      "공공API를 활용하여 미세먼지 데이터 공급",
      "Redux를 활용하여 데이터의 상태 관리",
      "localStorage에 즐겨찾기, 내 지역 정보 저장",
    ],
  },
  {
    id: "diary-calendar",
    name: "다이어리 캘린더",
    state: "OPEN",
    github: "https://github.com/tmdgp0212/Diary_Calendar",
    demoSite: "https://tmdgp0212.github.io/Diary_Calendar/",
    duration: "22.09.29 ~ 22.10.05",
    language: ["React"],
    library: [
      "redux",
      "redux-toolkit",
      "react-router-dom",
      "styled-components",
    ],
    worker: "1인",
    summary: "일기를 작성하고 관리 할 수 있는 달력형 다이어리입니다",
    works: [
      "다이어리를 작성하고, 수정하고, 삭제하는 로직을 redux를 활용하여 구현",
      "백엔드 서버가 없는 환경에서 작성한 일기 데이터를 저장하기 위해 LocalStorage를 활용하여 동일 브라우저 내 접속 시 작성 된 일기가 보존되어있도록 구현",
    ],
  },
  {
    id: "music-player",
    name: "Music Player",
    state: "OPEN",
    github: "https://github.com/tmdgp0212/30projects",
    demoSite: "https://peppy-eclair-b38986.netlify.app/",
    duration: "2일",
    language: ["React"],
    library: ["redux", "styled-component", "framer-motion"],
    worker: "1인",
    summary: "Audio API를 활용한 나만의 음악 플레이어 앱 METUBE MUSIC입니다.",
    works: [
      "Audio API를 활용하여 음악 플레이어를 구현",
      "Redux를 활용하여 재생중인 음악의 상태와 재생목록을 관리",
    ],
  },
  {
    id: "drawing-board",
    name: "Lets Draw!",
    state: "OPEN",
    github: "https://github.com/tmdgp0212/30projects",
    demoSite: "https://tranquil-semifreddo-5b67db.netlify.app/",
    duration: "2일",
    language: ["HTML", "SCSS", "Javascript"],
    library: [""],
    worker: "1인",
    summary: "Canvase API를 활용한 나만의 그림판 Lets Draw! 입니다.",
    works: [
      "Canvase API를 활용하여 그림판 구현",
      "canvas의 dataUrl을 받아 미니맵을 구현하고, 작품을 저장할 수 있도록 구현",
    ],
  },
  {
    id: "find-movie",
    name: "Find Movie",
    state: "OPEN",
    github: "https://github.com/tmdgp0212/FIND-MOVIE",
    demoSite: "https://tangerine-medovik-e674b3.netlify.app/",
    duration: "1일",
    language: ["HTML", "SCSS", "Javacript"],
    library: [""],
    worker: "1인",
    summary: "연도별 영화 검색이 가능한 영화 검색 사이트 입니다",
    works: [
      "순수 자바스크립트와 open API를 활용한 영화검색 페이지 구현",
      "스크롤에 바닥에 닿았을 때 다음 목록이 불러와지는 무한스크롤 기능 구현",
    ],
  },
];
