import { ProjectDetailType } from "../types/projectDetail";

export const projectDetail: ProjectDetailType[] = [
  {
    id: "yolda-user",
    name: "열다 서비스 페이지",
    state: "done",
    github: "",
    demoSite: "",
    duration: "",
    language: [],
    library: [],
    worker: "",
    summary: "",
    works: [],
  },
  {
    id: "yolda-admin",
    name: "열다 어드민 페이지",
    state: "done",
    github: "",
    demoSite: "",
    duration: "",
    language: [],
    library: [],
    worker: "",
    summary: "",
    works: [],
  },
  {
    id: "vacation-manager",
    name: "연차 관리 프로그램",
    state: "done",
    github: "",
    demoSite: "",
    duration: "",
    language: [],
    library: [],
    worker: "",
    summary: "",
    works: [],
  },
  {
    id: "moodlog",
    name: "Moodlog",
    state: "done",
    github: "",
    demoSite: "",
    duration: "",
    language: [],
    library: [],
    worker: "",
    summary: "",
    works: [],
  },
  {
    id: "next-furniture",
    name: "Next Furniture",
    state: "done",
    github: "",
    demoSite: "",
    duration: "",
    language: [],
    library: [],
    worker: "",
    summary: "",
    works: [],
  },
  {
    id: "fine-dust",
    name: "미세먼지 알리미",
    state: "done",
    github: "https://github.com/tmdgp0212/FineDustMap",
    demoSite: "https://whimsical-sfogliatella-62bbe0.netlify.app/",
    duration: "23.03.24 ~ 23.03.27",
    language: ["react"],
    library: ["redux", "axios", "react-router-dom", "styled-component"],
    worker: "1인",
    summary: "시/도별 미세먼지 정보를 조회할 수 있는 미세먼지 알리미 앱 입니다",
    works: [
      "공공API를 활용하여 미세먼지 데이터 공급",
      "Redux를 활용하여 데이터의 상태 관리",
      "localStorage에 즐겨찾기, 내 지역 정보 저장",
    ],
  },
  {
    id: "diary-calendar",
    name: "다이어리 캘린더",
    state: "done",
    github: "",
    demoSite: "",
    duration: "",
    language: [],
    library: [],
    worker: "",
    summary: "",
    works: [],
  },
  {
    id: "music-player",
    name: "Music Player",
    state: "done",
    github: "",
    demoSite: "",
    duration: "",
    language: [],
    library: [],
    worker: "",
    summary: "",
    works: [],
  },
  {
    id: "drawing-board",
    name: "Lets Draw!",
    state: "done",
    github: "",
    demoSite: "",
    duration: "",
    language: [],
    library: [],
    worker: "",
    summary: "",
    works: [],
  },
  {
    id: "find-movie",
    name: "Find Movie",
    state: "done",
    github: "",
    demoSite: "",
    duration: "",
    language: [],
    library: [],
    worker: "",
    summary: "",
    works: [],
  },
];
